#!/usr/bin/env python
"""Read-only environment report.

Prints what we can see about the local environment (Python version, venv,
package import status, ruff/pytest availability, ffmpeg/ffprobe presence,
models dir, persistent config path, Node/pnpm/cargo presence, Tauri
sidecar status, git status). Intended for fast triage when a check fails
and the agent (or human) wants to know what's reachable.

Never installs, downloads, deletes, or modifies anything.

Run:

    python scripts/doctor.py
"""

from __future__ import annotations

import importlib
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parents[1]


def _ok(label: str, value: str) -> None:
    print(f"  [ok]   {label}: {value}")


def _miss(label: str, hint: str = "") -> None:
    suffix = f" ({hint})" if hint else ""
    print(f"  [miss] {label}{suffix}")


def _info(label: str, value: str) -> None:
    print(f"  [info] {label}: {value}")


def _section(title: str) -> None:
    print()
    print(title)


def _which(cmd: str) -> Optional[str]:
    return shutil.which(cmd)


def _try_import(module: str) -> bool:
    try:
        importlib.import_module(module)
        return True
    except Exception:
        return False


def _run(cmd: list[str]) -> Optional[str]:
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
        if out.returncode == 0:
            return (out.stdout or out.stderr).strip().splitlines()[0] if (out.stdout or out.stderr) else ""
    except Exception:
        return None
    return None


def main() -> int:
    print("Srtforge doctor — environment report")
    print(f"  generated by {Path(__file__).relative_to(REPO_ROOT)}")
    print()

    _section("Platform")
    _info("OS", f"{platform.system()} {platform.release()} ({platform.machine()})")
    _info("Python", f"{sys.version.splitlines()[0]} at {sys.executable}")
    venv = os.environ.get("VIRTUAL_ENV")
    if venv:
        _ok("VIRTUAL_ENV", venv)
    else:
        _miss("VIRTUAL_ENV", "no venv active — `\\.venv\\Scripts\\Activate.ps1`")
    _info("Repo root", str(REPO_ROOT))

    _section("Project paths")
    for rel, hint in (
        ("models", "FV4 ckpt + cfg"),
        ("logs", "RunLogger output"),
        ("output", "default SRT output dir"),
        ("tmp", "scratch temp dir"),
        ("srtforge", "Python pipeline package"),
        ("srtforge-studio", "Tauri Studio GUI"),
        ("srtforge-studio/src-tauri/binaries", "PyInstaller worker sidecar lives here"),
    ):
        path = REPO_ROOT / rel
        if path.exists():
            _ok(rel, "present")
        else:
            _miss(rel, hint)

    _section("Persistent config")
    try:
        from srtforge.settings import get_persistent_config_path

        pcp = get_persistent_config_path()
        _info("path", str(pcp))
        _info("exists", "yes" if pcp.exists() else "no (defaults will be used)")
    except Exception as exc:
        _miss("srtforge.settings.get_persistent_config_path", str(exc))

    _section("Environment overrides")
    for key in (
        "SRTFORGE_CONFIG",
        "SRTFORGE_PERSISTENT_CONFIG",
        "SRTFORGE_PROJECT_ROOT",
        "SRTFORGE_FFMPEG_DIR",
        "HF_TOKEN",
        "GEMINI_API_KEY",
    ):
        val = os.environ.get(key)
        if val:
            # Don't dump secret values to stdout.
            if "TOKEN" in key or "KEY" in key:
                _info(key, "[set, value redacted]")
            else:
                _info(key, val)
        else:
            _info(key, "(unset)")

    _section("Python imports")
    for module in (
        "srtforge",
        "srtforge.cli",
        "srtforge.pipeline",
        "srtforge.settings",
        "srtforge.config",
        "srtforge.logging",
        "srtforge.ffmpeg",
        "srtforge.mux",
        "srtforge.post",
        "srtforge.post.srt_utils",
    ):
        if _try_import(module):
            _ok(module, "imports")
        else:
            _miss(module, "import failed")

    _section("Dev tooling")
    if _try_import("pytest"):
        _ok("pytest", "available")
    else:
        _miss("pytest", "pip install -e .[dev]")
    if _try_import("ruff"):
        _ok("ruff (module)", "available")
    elif _which("ruff"):
        _ok("ruff (cli)", _which("ruff") or "")
    else:
        _miss("ruff", "pip install -e .[dev]")

    _section("Native tooling")
    for cmd, hint in (
        ("ffmpeg", "audio extraction / mux / burn"),
        ("ffprobe", "stream metadata"),
        ("mkvmerge", "Matroska soft-embed (optional)"),
        ("git", "version control"),
        ("node", "Tauri Studio JS runtime"),
        ("pnpm", "Tauri Studio package manager"),
        ("cargo", "Tauri Studio Rust shell"),
    ):
        path = _which(cmd)
        if path:
            ver = _run([cmd, "--version"]) or ""
            _ok(cmd, f"{path} ({ver})" if ver else path)
        else:
            _miss(cmd, hint)

    _section("Tauri sidecar binary")
    sidecar = REPO_ROOT / "srtforge-studio" / "src-tauri" / "binaries" / (
        "srtforge_worker-x86_64-pc-windows-msvc.exe"
        if os.name == "nt"
        else "srtforge_worker-x86_64-unknown-linux-gnu"
    )
    if sidecar.exists():
        try:
            size_mb = sidecar.stat().st_size / (1024 * 1024)
            _ok(sidecar.name, f"present ({size_mb:.1f} MiB)")
        except OSError:
            _ok(sidecar.name, "present")
    else:
        _miss(sidecar.name, "rebuild via packaging/windows/srtforge_worker.spec")

    _section("Git status")
    if _which("git"):
        try:
            r = subprocess.run(
                ["git", "status", "--short"],
                capture_output=True,
                text=True,
                cwd=str(REPO_ROOT),
                timeout=10,
            )
            if r.returncode == 0:
                lines = (r.stdout or "").rstrip().splitlines()
                if not lines:
                    _info("status", "clean")
                else:
                    _info("status", f"{len(lines)} entries")
                    for line in lines[:10]:
                        print(f"           {line}")
                    if len(lines) > 10:
                        print(f"           ... {len(lines) - 10} more")
            else:
                _info("status", f"git returned {r.returncode}")
        except Exception as exc:
            _info("status", f"unavailable ({exc})")
    else:
        _info("status", "git not on PATH")

    print()
    print("doctor done — this script does not modify anything.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
